trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
stages:
- stage: dev
  jobs:
    - job: devjob
      steps:
        - bash: echo devdevelopy